/**
 * The thought of the day library.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * Ported verbatim from the app
 *
 * This is the `_thoughts` list in `lib/core/constants/thoughts_365.dart` from
 * the Flutter repo, converted mechanically rather than retyped. Both surfaces
 * have to land on the *same* line for a given day — the phone and the web app
 * are one product, and a member who reads the dashboard in a browser at work
 * and on their phone at night should not be given two different thoughts. If
 * the list changes there, regenerate here.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * Why the site carries the list at all
 *
 * The web dashboard used to render only what an operator had published, which
 * meant a blank space on every day nobody had set one. The rotation is the
 * default behaviour and the override is the exception, so the default has to
 * be something the client can work out for itself — the same reason the app
 * ships these in its binary.
 */

export const THOUGHTS: readonly string[] = [
  "Peace is not the absence of conflict, but the ability to cope with it through inner strength.",
  "Every moment is a fresh beginning. Use it to create something beautiful.",
  "The soul's natural state is one of peace, love, and happiness.",
  "When you change your thoughts, you change your world.",
  "Meditation is not about stopping thoughts, but recognizing that you are more than your thoughts.",
  "Quiet the mind, and the soul will speak.",
  "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
  "Happiness is not something readymade. It comes from your own actions.",
  "Peace begins with a smile.",
  "Be here now. Be content with what you have.",
  "In the middle of difficulty lies opportunity.",
  "The root of all wellness is a peaceful mind.",
  "You are a soul, a spark of light. Let your light shine.",
  "Breathe in peace, breathe out love.",
  "Gratitude turns what we have into enough.",
  "Self-care is not selfish; it is essential for the soul.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Simplicity is the ultimate sophistication of the mind.",
  "Acceptance of the present moment is the gateway to inner peace.",
  "Kindness is a language which the deaf can hear and the blind can see.",
  "What you think, you become. What you feel, you attract.",
  "Your heart is the size of an ocean. Go find yourself in its hidden depths.",
  "To understand everything is to forgive everything.",
  "The only journey is the journey within.",
  "Out of difficulties grow miracles.",
  "Nothing can bring you peace but yourself.",
  "Act as if what you do makes a difference. It does.",
  "Listen to the silence, it has so much to say.",
  "Let go of what was, accept what is, and trust what will be.",
  "Every day is a gift. Open it with gratitude.",
  "Believe you can and you're halfway there.",
  "Start where you are. Use what you have. Do what you can.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "Forgiveness is the key to action and freedom.",
  "He who has a why to live can bear almost any how.",
  "Peace is its own reward.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Speak only when your words are more beautiful than silence.",
  "Be the change that you wish to see in the world.",
  "Peace of mind is that state in which you have accepted the worst.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Life is a journey, not a destination.",
  "Love is the absence of judgment.",
  "Small acts of kindness make a big difference.",
  "The greatest wealth is contentment.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Where there is love there is life.",
  "Choose peace today.",
  "One day at a time.",
  "Your calm mind is the ultimate weapon against your challenges.",
  "All that we are is the result of what we have thought.",
  "You must do the things you think you cannot do.",
  "The wound is the place where the Light enters you.",
  "Live in the sunshine, swim the sea, drink the wild air.",
  "The mind is everything. What you think you become.",
  "Be happy for this moment. This moment is your life.",
  "Progress is measured by the degree of inner peace.",
  "Happiness is when what you think, what you say, and what you do are in harmony.",
  "Turn your wounds into wisdom.",
  "Be a lamp, a lifeboat, or a ladder. Help someone's soul heal.",
  "A disciplined mind brings happiness.",
  "To love oneself is the beginning of a lifelong romance.",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.",
  "True peace is not merely the absence of tension: it is the presence of justice.",
  "Your vision will become clear only when you can look into your own heart.",
  "Wellness is a connection of path, body, and spirit.",
  "Let the beauty of what you love be what you do.",
  "The soul is cured by being with children.",
  "The soul always knows what to do to heal itself.",
  "Patience is the companion of wisdom.",
  "The spirit is stronger than any circumstance.",
  "Quiet minds cannot be perplexed or frightened.",
  "There is no path to peace. Peace is the path.",
  "Be gentle with yourself. You are a child of the universe.",
  "Light tomorrow with today.",
  "Calmness is the cradle of power.",
  "Gratitude is the fairest blossom which springs from the soul.",
  "Look deep into nature, and then you will understand everything better.",
  "Do not seek to follow in the footsteps of the wise. Seek what they sought.",
  "He who is contented is rich.",
  "Peace is a daily, a weekly, a monthly process, gradually changing opinions, slowly eroding old barriers.",
  "Inner peace begins the moment you choose not to allow another person or event to control your emotions.",
  "The inner life is not something before, after, or beyond everyday existence. It is the life itself.",
  "Within you, there is a stillness and a sanctuary to which you can retreat at any time.",
  "The soul that sees beauty may sometimes walk alone.",
  "The greatest effort is not to be successful, but to be true to oneself.",
  "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
  "Quiet reflection is the gateway to self-discovery.",
  "To perform every action with an attitude of dedication is yoga.",
  "The greatest prayer is patience.",
  "Wisdom begins in wonder.",
  "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.",
  "Choose to be optimistic, it feels better.",
  "Peace comes from within. Do not seek it without.",
  "The standard of success is absolutely the amount of joy you feel.",
  "When we feed our souls, we nourish our lives.",
  "You are the sky. Everything else is just the weather.",
  "The purpose of our lives is to be happy.",
  "Nothing is permanent in this wicked world, not even our troubles.",
  "We do not inherit the earth from our ancestors; we borrow it from our children.",
  "A quiet conscience makes one strong.",
  "He who is filled with love is filled with God himself.",
  "The only true wisdom is in knowing you know nothing.",
  "Peace is the simplicity of heart that makes us love all creatures.",
  "The soul is the mirror of an honest heart.",
  "Be still and know.",
  "Live simply so that others may simply live.",
  "No medicine cures what happiness cannot.",
  "In the depth of winter, I finally learned that within me there lay an invincible summer.",
  "Our life is shaped by our mind; we become what we think.",
  "Faith is taking the first step even when you don't see the whole staircase.",
  "Never be in a hurry; do everything quietly and in a calm spirit.",
  "An unexamined life is not worth living.",
  "Peace is the morning star of the soul.",
  "The key to growth is the introduction of higher dimensions of consciousness into our awareness.",
  "Learn to let go. That is the key to happiness.",
  "To be beautiful means to be yourself. You don't need to be accepted by others.",
  "Give yourself permission to be peaceful.",
  "Real peace is always unshakable.",
  "May your mind be calm and your heart be open.",
  "A warm smile is the universal language of kindness.",
  "Act without expectation.",
  "The journey of a thousand miles begins with one step.",
  "He who controls others may be powerful, but he who has mastered himself is mightier still.",
  "If you want to fly, you have to give up the things that weigh you down.",
  "You are never alone. The universe is always supporting you.",
  "Keep your heart open to the wonders of life.",
  "Peace is the result of retraining your mind to process life as it is.",
  "Silence is a source of great strength.",
  "Your life is your message to the world. Make it inspiring.",
  "Find peace in the simple things.",
  "Choose kind thoughts, they build a happy life.",
  "Purity of mind is the greatest pilgrimage.",
  "A grateful heart is a magnet for miracles.",
  "The soul is the truth of who we are.",
  "Let your heart guide you, it knows the way.",
  "Do good, and the good will return to you.",
  "Peace is a state of being, not a set of circumstances.",
  "May you find peace in every breath.",
  "Walk as if you are kissing the Earth with your feet.",
  "Your inner light can never be extinguished.",
  "Every step is a path to peace.",
  "Trust the process of life.",
  "Be the light in someone else's darkness.",
  "Peace is the beauty of the soul.",
  "Focus on the good, and the good will expand.",
  "You are a divine spark of light.",
  "Let love be your guide.",
  "Your soul is eternal and peaceful.",
  "Quiet the mind, open the heart.",
  "Speak with kindness, act with love.",
  "Peace is here, peace is now.",
  "Happiness is a warm glow inside.",
  "The soul is the source of all joy.",
  "Breathe in light, breathe out peace.",
  "Your thoughts are the seeds of your destiny.",
  "Let peace fill your soul.",
  "Be kind to yourself, you are doing your best.",
  "Choose peace, choose love, choose joy.",
  "You are a beacon of light.",
  "Find stillness within the storm.",
  "Let your soul shine bright.",
  "Every breath is a reminder of life.",
  "Peace is the song of the heart.",
  "Walk in peace, speak in love.",
  "Your mind is a sacred space.",
  "Let go of what you cannot control.",
  "A peaceful heart is a happy heart.",
  "Gratitude is the language of the soul.",
  "Choose to see the beauty in everything.",
  "You are capable of great peace.",
  "Let peace guide your actions.",
  "May you be filled with loving-kindness.",
  "Your soul is at peace.",
  "Choose love over fear.",
  "Find joy in the present moment.",
  "Your light is needed in the world.",
  "Breathe, trust, and let go.",
  "Peace is your birthright.",
  "Let your heart sing.",
  "Walk with grace and gratitude.",
  "You are a peaceful soul.",
  "Rest in the silence of your soul.",
  "Every day is a new beginning.",
  "Find the peace that lies within.",
  "Your soul is beautiful and pure.",
  "Let love flow through you.",
  "Be present in all that you do.",
  "Peace is a gift you give to yourself.",
  "Let your mind be still like a lake.",
  "Choose peace in every moment.",
  "You are a channel of peace.",
  "Trust the wisdom of your heart.",
  "Every day brings new opportunities for growth.",
  "Let go of worry and find peace.",
  "Your soul is full of light and love.",
  "Breathe in peace, exhale tension.",
  "May your day be filled with peace.",
  "Find strength in your stillness.",
  "Your heart is a sanctuary of peace.",
  "Choose to respond with love.",
  "You are a reflection of divine peace.",
  "Let the light of peace guide you.",
  "Be still and listen to your heart.",
  "Peace is the natural flow of life.",
  "You are supported by the universe.",
  "Let your soul be at peace.",
  "Every breath is a gift of peace.",
  "Choose kindness today.",
  "Your mind is calm and peaceful.",
  "May you find joy in your journey.",
  "Walk in the light of peace.",
  "You are peace itself.",
  "Let your heart be light.",
  "Every moment is an opportunity to practice peace.",
  "Find comfort in the stillness.",
  "Your soul is a source of infinite peace.",
  "Let love guide your thoughts.",
  "Be gentle with your mind.",
  "Peace is a state of mind, not a place.",
  "Let your soul be filled with gratitude.",
  "Choose to focus on the present.",
  "You are surrounded by peace.",
  "Trust your inner guidance.",
  "Every day is a step on the road inward.",
  "Let go of anger and choose peace.",
  "Your soul is connected to the divine.",
  "Breathe in calm, breathe out stress.",
  "May you experience deep peace today.",
  "Find clarity in your quiet moments.",
  "Your heart is open to receive peace.",
  "Choose to speak words of peace.",
  "You are a peaceful being of light.",
  "Let the peace within you radiate outward.",
  "Be at peace with where you are.",
  "Peace is the foundation of happiness.",
  "You are strong, resilient, and peaceful.",
  "Let your soul find rest.",
  "Every step you take can be a step of peace.",
  "Choose compassion today.",
  "Your mind is a peaceful sanctuary.",
  "May you walk in peace all the days of your life.",
  "Celebrate the peace of this moment.",
  "You are a peaceful soul, always.",
  "Keep your heart pure and your mind calm.",
  "Peace is the greatest treasure.",
  "Every day is a chance to start fresh.",
  "Find peace in your daily routine.",
  "Your soul is a beacon of hope and peace.",
  "Let love heal your heart.",
  "Be patient with your growth.",
  "Peace is the quiet voice within.",
  "Let your soul be your guide.",
  "Choose peace, even when it is difficult.",
  "You are full of light, love, and peace.",
  "Trust the timing of your life.",
  "Every experience is a lesson for the soul.",
  "Let go of expectations and find peace.",
  "Your soul is connected to all that is.",
  "Breathe in serenity, breathe out worry.",
  "May your mind be filled with peaceful thoughts.",
  "Find joy in the simple act of breathing.",
  "Your heart is a magnet for peace.",
  "Choose to see the good in others.",
  "You are a force for peace in the world.",
  "Let the peace of God rule in your heart.",
  "Be gentle with your soul.",
  "Peace is the sweet fruit of love.",
  "You are safe, loved, and at peace.",
  "Let your soul dance with joy.",
  "Every moment of peace counts.",
  "Choose to be a source of peace.",
  "Your mind is quiet, still, and calm.",
  "May you find peace that passes understanding.",
  "Walk gently upon the Earth.",
  "Peace is a choice you make every day.",
  "Every day is an opportunity to love.",
  "Find peace in the midst of chaos.",
  "Your soul is pure, bright, and peaceful.",
  "Let love be the anchor of your soul.",
  "Be kind to all living beings.",
  "Peace is the rhythm of the universe.",
  "Let your soul be filled with light.",
  "Choose to let go of the past.",
  "You are a unique and beautiful soul.",
  "Trust that all is well.",
  "Every day is a gift of grace.",
  "Let go of the need to control.",
  "Your soul is a spark of the divine.",
  "Breathe in peace, breathe out peace.",
  "May your heart be filled with peace.",
  "Find peace in your reflections.",
  "Your mind is open to peaceful ideas.",
  "Choose to think thoughts of peace.",
  "You are a peaceful warrior of light.",
  "Let the light of love shine through you.",
  "Be still and know that you are peace.",
  "Peace is the path of the wise.",
  "You are protected, guided, and at peace.",
  "Let your soul sing its song.",
  "Every breath brings you closer to peace.",
  "Choose to be a messenger of peace.",
  "Your mind is a peaceful oasis.",
  "May your life be a reflection of peace.",
  "Seek the peace that is always there.",
  "Give thanks for the peace in your life.",
  "Peace is the harvest of a quiet mind.",
  "Every day is a blessing from above.",
  "Find peace in the beauty of nature.",
  "Your soul is a temple of peace.",
  "Let love be your daily practice.",
  "Be a friend to your mind.",
  "Peace is the quiet harmony of the soul.",
  "Let your soul be filled with joy.",
  "Choose to accept what you cannot change.",
  "You are a peaceful, loving soul.",
  "Trust in the path of your life.",
  "Every step is a path of light.",
  "Let go of fear and choose love.",
  "Your soul is connected to the source.",
  "Breathe in love, breathe out peace.",
  "May your days be peaceful and bright.",
  "Find peace in your gratitude.",
  "Your mind is calm like a quiet ocean.",
  "Choose to speak with a peaceful voice.",
  "You are a source of comfort and peace.",
  "Let the peace within you shine bright.",
  "Be at peace with your past.",
  "Peace is the way of the heart.",
  "You are loved, cherished, and at peace.",
  "Let your soul feel the peace.",
  "Every moment of peace is a victory.",
  "Choose to build a peaceful world.",
  "Your mind is relaxed and peaceful.",
  "May peace be with you, always.",
  "Remember that your true nature is peace.",
  "Peace is the greatest gift you can share.",
  "Every day is a new opportunity to shine.",
  "Find peace in your silent prayers.",
  "Your soul is a shining light of peace.",
  "Let love rule your heart.",
  "Be gentle with your journey.",
  "Peace is the ultimate wellness.",
  "Let your soul rest in quietness.",
  "Choose to see the light in everyone.",
  "You are a peaceful presence.",
  "Trust the guidance of the divine.",
  "Every day is a step closer to self-realization.",
  "Let go of the outcome and trust.",
  "Your soul is full of peace and wisdom.",
  "Breathe in peace, breathe out gratitude.",
  "May you find deep peace within.",
  "Find peace in your relationships.",
  "Your mind is in harmony with your soul.",
  "Choose to act from a place of peace.",
  "You are a channel of divine love and peace.",
  "Let peace be your legacy.",
  "Be still and feel the peace.",
  "Peace is the destination of the soul.",
  "You are safe, secure, and peaceful.",
  "Let your soul be your guiding star.",
  "Every day is a celebration of peace.",
  "Choose to be a beacon of peace.",
  "Your mind is a peaceful sanctuary of love.",
  "May you live in peace, now and forever.",
  "Quiet is not somewhere you go. It is somewhere you already live.",
];

/**
 * Day of the year, 1–366, in the reader's own timezone.
 *
 * Local rather than UTC, and matching `Thoughts365.dayOfYear` in the app: the
 * day somebody is living in is the one on their own clock, and a UTC day would
 * roll the thought over at 5:30am in India.
 */
export function dayOfYear(date: Date): number {
  const startOfYear = new Date(date.getFullYear(), 0, 1);
  const startOfDay = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.round((startOfDay.getTime() - startOfYear.getTime()) / 86_400_000) + 1;
}

/** `YYYY-MM-DD` in local time — the stamp an operator's override carries. */
export function dateKey(date: Date): string {
  const pad = (n: number) => `${n}`.padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

export function thoughtForDay(date: Date): string {
  return THOUGHTS[(dayOfYear(date) - 1) % THOUGHTS.length];
}
